import { expect, test, type Page } from '@playwright/test'

async function injectFakeSession(page: Page) {
  await page.addInitScript(() => {
    localStorage.setItem('jb2026.accessToken', 'smoke-test-fake-token')
    localStorage.setItem(
      'jb2026.sessionProfile',
      JSON.stringify({ userId: 'test', displayName: 'Smoke Test', email: 'smoke@test.local', role: 'Admin' }),
    )
  })
}

async function mockBillingRoutes(page: Page, state: { lookupBodies: any[] }) {
  await page.route('**/ui/feature-flags', (route) => route.fulfill({ json: { flags: [] } }))

  await page.route('**/api/v2/user-profiles/me', (route) =>
    route.fulfill({
      json: {
        userId: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
        username: 'admin',
        displayName: 'Administrator',
        role: 'Admin',
      },
    }),
  )

  await page.route('**/api/v2/settings', async (route) => {
    await route.fulfill({
      json: {
        companyName: 'JB2026 Printing',
        timeZone: 'Asia/Kuala_Lumpur',
        currencyCode: 'MYR',
        enableLegacyFallback: true,
      },
    })
  })

  await page.route('**/api/v2/billing/clients**', (route) =>
    route.fulfill({
      json: {
        clients: [
          {
            externalClientId: 'client-1',
            displayName: 'Acme Billing',
          },
        ],
      },
    }),
  )

  await page.route('**/api/v2/billing/invoices/autofill-lookup', async (route) => {
    const body = route.request().postDataJSON()
    state.lookupBodies.push(body)

    const canonicalJobNumbers = body.canonicalJobNumbers as string[]
    const jobs = canonicalJobNumbers.map((jobNumber) => {
      if (jobNumber === '999999-1') {
        return {
          canonicalJobNumber: jobNumber,
          purchaseOrder: '',
          productDetails: '',
          description: '',
          status: 'Unresolved',
          message: 'Job number could not be resolved.',
        }
      }

      if (jobNumber === '168825-1') {
        return {
          canonicalJobNumber: jobNumber,
          orderId: 'job-168825-1',
          purchaseOrder: 'PO-825',
          productDetails: '2.尺寸：\nN/A',
          description: '',
          status: 'ResolvedButMissingSection1',
          message: 'Section 1 could not be extracted. Manual review required.',
        }
      }

      const purchaseOrder = {
        '168824-1': 'PO-001',
        '168824-2': 'PO-002',
        '168824-3': 'PO-003',
        '168900-1': 'PO-900',
      }[jobNumber] ?? 'PO-000'

      return {
        canonicalJobNumber: jobNumber,
        orderId: `job-${jobNumber}`,
        purchaseOrder,
        productDetails: '1.印刷內容：\nDescription',
        description: `Description for ${jobNumber}`,
        status: 'Resolved',
        message: '',
      }
    })

    await route.fulfill({ json: { jobs } })
  })

  await page.route('**/api/v2/billing/invoices', async (route) => {
    if (route.request().method() === 'GET') {
      await route.fulfill({ json: { invoices: [] } })
      return
    }

    await route.fulfill({
      status: 201,
      json: {
        billingSummary: {
          externalInvoiceId: 'invoice-1',
          invoiceNumber: 'INV-001',
          clientName: 'Acme Billing',
          invoiceDate: '2026-05-25',
          amount: 0,
          status: 'Draft',
        },
      },
    })
  })
}

test.describe('Billing invoice editor autofill', () => {
  test('parses job number expressions and only refreshes on explicit action', async ({ page }) => {
    const state = { lookupBodies: [] as any[] }
    await injectFakeSession(page)
    await mockBillingRoutes(page, state)

    await page.goto('/app/billing/invoices')
    await page.getByRole('button', { name: 'New Invoice' }).click()

    await expect(page.getByRole('dialog').getByText('New Invoice', { exact: true })).toBeVisible()
    await expect(page.locator('.line-items-table tbody tr')).toHaveCount(1)

    await page.getByLabel('Job Number').fill('168824-1/2/3, 168825-1')
    await expect(page.getByRole('button', { name: 'Refresh from Job Numbers' })).toBeVisible()
    await expect.poll(() => state.lookupBodies.length).toBe(0)

    await page.getByRole('button', { name: 'Refresh from Job Numbers' }).click()

    await expect.poll(() => state.lookupBodies.length).toBe(1)
    await expect(state.lookupBodies[0].canonicalJobNumbers).toEqual([
      '168824-1',
      '168824-2',
      '168824-3',
      '168825-1',
    ])
    await expect(page.locator('.line-items-table tbody tr')).toHaveCount(4)
  })

  test('requires confirmation before overwriting dirty autogenerated rows', async ({ page }) => {
    const state = { lookupBodies: [] as any[] }
    await injectFakeSession(page)
    await mockBillingRoutes(page, state)

    await page.goto('/app/billing/invoices')
    await page.getByRole('button', { name: 'New Invoice' }).click()

    await page.getByLabel('Job Number').fill('168824-1/2')
    await page.getByRole('button', { name: 'Refresh from Job Numbers' }).click()
    await expect.poll(() => state.lookupBodies.length).toBe(1)

    await page.locator('textarea').first().fill('Custom manual change')
    await page.getByLabel('Job Number').fill('168900-1')
    await page.getByRole('button', { name: 'Refresh from Job Numbers' }).click()

    await expect(page.getByText('You have manual changes in your invoice items. Regenerating from Job Numbers will overwrite them. Proceed?')).toBeVisible()
    await expect.poll(() => state.lookupBodies.length).toBe(1)

    await page.getByRole('button', { name: 'Refresh from Job Numbers' }).last().click()

    await expect.poll(() => state.lookupBodies.length).toBe(2)
    await expect(page.locator('.line-items-table tbody tr')).toHaveCount(1)
    await expect(page.locator('input[value="PO-900"]')).toBeVisible()
  })

  test('shows unresolved and manual-review autofill feedback', async ({ page }) => {
    const state = { lookupBodies: [] as any[] }
    await injectFakeSession(page)
    await mockBillingRoutes(page, state)

    await page.goto('/app/billing/invoices')
    await page.getByRole('button', { name: 'New Invoice' }).click()

    await page.getByLabel('Job Number').fill('168824-1, 168825-1, 999999-1')
    await page.getByRole('button', { name: 'Refresh from Job Numbers' }).click()

    await expect(page.getByText('These job numbers could not be resolved: 999999-1')).toBeVisible()
    await expect(page.getByText('These job numbers require manual review because section 1 could not be extracted: 168825-1')).toBeVisible()
    await expect(page.getByText('Manual review required: section 1 description is blank.')).toBeVisible()
  })
})