namespace JB2026.Api.Services;

public interface IJobOrderStoredProcedureGateway
{
    Task<JobOrderStoredProcedureRecord?> SelectAsync(Guid orderId, CancellationToken cancellationToken = default);

    Task<Guid> InsertAsync(CreateJobOrderStoredProcedureRequest request, CancellationToken cancellationToken = default);

    Task<bool> UpdateAsync(UpdateJobOrderStoredProcedureRequest request, CancellationToken cancellationToken = default);

    Task<bool> DeleteAsync(Guid orderId, CancellationToken cancellationToken = default);
}

public sealed record JobOrderStoredProcedureRecord(
    Guid OrderId,
    int OrderType,
    string? OrderNumber,
    int? JobNumber,
    string? CustomerName,
    string? CustomerRef,
    string? OrderTitle,
    string? ProductCode,
    string? ProductStyle,
    string? ProductDetails,
    DateTime? OrderedOn,
    string? OrderedBy,
    string? OutputRef,
    string? InvoiceRef,
    decimal? InvoiceAmount,
    decimal? Qty,
    string? QtyText,
    DateTime? RequiredOn,
    DateTime? CompletedOn,
    string? SONumber,
    string? PONumber,
    string? OriginalSONumber,
    string? OriginalPONumber,
    string? PaymentTerms,
    string? Remarks,
    int Status,
    DateTime CreatedOn,
    Guid CreatedBy,
    DateTime ModifiedOn,
    Guid ModifiedBy,
    bool Retired,
    DateTime? RetiredOn,
    Guid? RetiredBy);

public sealed record CreateJobOrderStoredProcedureRequest(
    int OrderType,
    string? OrderNumber,
    int? JobNumber,
    string? CustomerName,
    string? CustomerRef,
    string? OrderTitle,
    string? ProductCode,
    string? ProductStyle,
    string? ProductDetails,
    DateTime? OrderedOn,
    string? OrderedBy,
    string? OutputRef,
    string? InvoiceRef,
    decimal? InvoiceAmount,
    decimal? Qty,
    string? QtyText,
    DateTime? RequiredOn,
    DateTime? CompletedOn,
    string? SONumber,
    string? PONumber,
    string? OriginalSONumber,
    string? OriginalPONumber,
    string? PaymentTerms,
    string? Remarks,
    int Status,
    DateTime? CreatedOn,
    Guid? CreatedBy,
    DateTime? ModifiedOn,
    Guid? ModifiedBy,
    bool Retired,
    DateTime? RetiredOn,
    Guid? RetiredBy);

public sealed record UpdateJobOrderStoredProcedureRequest(
    Guid OrderId,
    int OrderType,
    string? OrderNumber,
    int? JobNumber,
    string? CustomerName,
    string? CustomerRef,
    string? OrderTitle,
    string? ProductCode,
    string? ProductStyle,
    string? ProductDetails,
    DateTime? OrderedOn,
    string? OrderedBy,
    string? OutputRef,
    string? InvoiceRef,
    decimal? InvoiceAmount,
    decimal? Qty,
    string? QtyText,
    DateTime? RequiredOn,
    DateTime? CompletedOn,
    string? SONumber,
    string? PONumber,
    string? OriginalSONumber,
    string? OriginalPONumber,
    string? PaymentTerms,
    string? Remarks,
    int Status,
    DateTime? CreatedOn,
    Guid? CreatedBy,
    DateTime? ModifiedOn,
    Guid? ModifiedBy,
    bool Retired,
    DateTime? RetiredOn,
    Guid? RetiredBy);
