<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Fonts/Lato-Regular.ttf" />
    <EmbeddedResource Include="Fonts/NotoSansCJKsc-Regular.otf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QuestPDF" Version="2026.2.4" />
  </ItemGroup>

</Project>
