<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\JB2026.Infrastructure\JB2026.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="ClientApp\node_modules\**" />
    <None Remove="ClientApp\node_modules\**" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
